### ISSUE TITLE
Namespace class definition not found (v 1.8.0)

### ISSUE THREAD

**Issue by aormsby** [redundent/kotlin-xml-builder#52]
Some context - I added your builder v1.8.0 to a gradle plugin I'm writing. I ran a quick test to see if I could generate a basic XML file with a Namespace. My code:

```kotlin
val namespace = Namespace("android", "http://schemas.android.com/apk/res/android") 
val xml = xml("locale-config", namespace = namespace) { }
```

But it always fails trying access the Namespace class. Error:

`Caused by: java.lang.NoClassDefFoundError: org/redundent/kotlin/xml/Namespace`

Not sure why this would be happening. Would be a shame if this prevented me from using your plugin, seems quite handy. Let me know if I can provide any more specific info for you.

**Comment by redundent** [comment]
Hey @aormsby ,
Can you provide how you are including the lib in your plugin? NoClassDefFoundError seems very fishy.

**Comment by aormsby** [comment]
Hey yeah, just started checking on that. I had included it as `compileOnly` in my plugin, and a switch to something like `implementation` did work. Now just determining the best keyword option in this case.

But if I had included the builder in a project directly, `compileOnly` would have been okay? Just seems odd that I'd have to use a different keyword in an external plugin that still gets applied to the project.

**Comment by aormsby** [comment]
Also, I'm only interested in generating the XML at compile time, and I don't want your builder added to the build output in this case. So I would think `compileOnly` would be the way to go, and I'm wondering why that wouldn't work here.

**Comment by redundent** [comment]
I haven't written many gradle plugins, maybe 1 or 2, so I'm not too familiar with the best solution, but I'll try.
Since this is a gradle plugin, which project are you referring to when you say compile time? The gradle plugn compile or the project that includes it? Given the error and the solution, it sounds like the code is executing when the including project is being built, which means you would need `implementation`.

**Comment by aormsby** [comment]
I'm also somewhat new to Gradle plugins, but I'll do my best to explain what I understand. To begin, since I'm working on a plugin for an Android project, I think my dependency config options are somewhat limited compared to what Gradle usually offers. Here's an Android doc on the available keywords for reference - https://developer.android.com/studio/build/dependencies#dependency_configurations

There are two main use cases for a gradle dependency - compile (build) time and runtime (in the build output). The plugin I'm writing serves a simple purpose. During the pre-build phase (compile time), generate an XML resource file and a couple of Kotlin files to be included in the build output so they can be included in a project at runtime. To do this, I'm your XML builder and a Kotlin code generator (KotlinPoet), both of which are external dependencies.

My current dependency configuration:

```kotlin
dependencies {
    compileOnly("com.android.tools.build:gradle:7.3.1")
    compileOnly("com.squareup:kotlinpoet:1.12.0")
    implementation("org.redundent:kotlin-xml-builder:1.8.0")
}
```

For KotlinPoet, I included it in my plugin as `compileOnly` because I need to access the library during the build, but it's not needed at runtime at all. And I don't want to accidentally provide that library to someone at runtime because they don't need (or want) it included in their application. If I included it with `implementation`, KotlinPoet would be included at runtime as unwanted bloat. But we only need it during build/compilation, so I use `compileOnly`

I _also_ don't want to include your XML builder in someone's project if they decide to use my gradle plugin, but all other workable keywords in this case - `implementation, api` - also send the dependency into the build output. I just don't want that if I can avoid it. (Also, the `compile` option you use is deprecated for me, but `api` replaces it.)

What I don't really know is _why_ your builder seems to require that. It's possible I'm misunderstanding something about Gradle here, but so far I don't think so. I did notice that some of the dependencies in your builder use `implementation`, and I wonder if that creates a requirement for me to also use `implementation`.

My

**Comment by redundent** [comment]
Without seeing exactly how you are using things, I can only speculate but it sounds like you are trying to generate the xml during the build time of the android project. Using `implementation` in your plugin project won't include those libraries in the runtime of the android application. `compileOnly` in the plugin project will only make that lib available to the compile classpath when the plugin is being built. It won't make it available to any project consuming the plugin. If the xml needs to be generated at built time of the android project, you will need `implementation` to make sure the lib gets added to the dependencies of the plugin's pom file.
The transitive dependencies of a plugin only get added to the buildScript classpath of the android project, not the actual application's dependencies so you shouldn't get any extra bloat in the resulting android package.
As to why KotlinPoet seems to work with `compileOnly`, I can't really say because I'm not familiar with that library.
If my assumptions are accurate, using `implementation` for kotlin-xml-builder in the plugin makes sense.

**Comment by aormsby** [comment]
Okay yeah, what you're saying makes sense. I think. Gradle dependency resolution is quite intricate and is still trickly for me.

> Using implementation in your plugin project won't include those libraries in the runtime of the android application.

Out of sheer curiosity, I will check this and confirm. But what you're saying sounds right in this context.

> As to why KotlinPoet seems to work with compileOnly, I can't really say

Me neither! It's especially odd, because it doesn't match up with the way you described everything else. This is mostly why I still have room for doubt, but it's possible I won't get to the bottom of this without deeper investigation.

**Comment by aormsby** [comment]
Okay, checked some things.

1. The xml builder doesn't show up in the APK of an Android project that consumes my plugin. You were totally right there, and that's great.
2. I found [clearer docs](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph) on the Gradle website about what configs the Java plugin provides (have to scroll down a bit from link for the configs chart)

From both your explanation and the docs here, I do agree that `implementation` should be totally safe regarding my concerns about supplying it to projects consuming my plugin. I still have no idea why `compileOnly` works for KotlinPoet, but I may even change that just to be safe.

I think I was really missing a key aspect of all this - I'm writing a _plugin_, not providing a library. If I was providing a library, perhaps the dependency config would make a difference, but the plugin isn't actually being consumed. It's just adding tasks! I feel like I understand this better now.

Thanks for helping and explaining!
